In [3]:
import numpy as np

In [4]:
data = np.loadtxt('data/movies/ratings.dat', delimiter='::', dtype=np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [5]:
data[:5,:] #UserId, MovieId, Rating, TimeStamp

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [6]:
data.shape

(1000209, 4)

In [7]:
mean_rating_total = data[:,2].mean()
mean_rating_total

3.581564453029317

In [8]:
user_ids = np.unique(data[:,0])
user_ids

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [9]:
mean_values=[] #userId 와 user별 영화 평점이 들어갈 리스트

for user_id in user_ids:
    data_for_user = data[data[:,0]==user_id, : ]
    value = data_for_user[:,2].mean()
    mean_values.append([user_id,value])

In [11]:
mean_values[:10]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

In [13]:
mean_array=np.array(mean_values,dtype=np.float32)
print(mean_array[:5])
print(mean_array.shape)

[[1.        4.188679 ]
 [2.        3.7131784]
 [3.        3.9019608]
 [4.        4.1904764]
 [5.        3.1464646]]
(6040, 2)


In [18]:
np.savetxt('data/movies/result.csv',mean_array,fmt='%.2f', delimiter=',')

In [19]:
movie_ids = np.unique(data[:,1])

In [23]:
m_mean_values=[]

for movie_id in movie_ids:
    data_for_mv = data[data[:,1]==movie_id,:]
    value = data_for_mv[:,2].mean()
    m_mean_values.append([movie_id, value])

In [25]:
m_mean_values[:5]

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566]]