In [1]:
import numpy as np
# 5행 1열 입력데이터(x)와 정답데이터(t)
x_data = np.array([1,2,3,4,5]).reshape(5,1)
t_data = np.array([2,3,4,5,6]).reshape(5,1)

# row_data = [[1,2],[2,3],[3,4],[4,5],[5,6]]


In [24]:
W= np.random.rand(1,1) #0-1 사이 랜덤 값
b= np.random.rand(1)

print('W=',W, 'b=',b)

W= [[0.88554314]] b= [0.68695527]


In [13]:
# 손실함수 공식
def loss_func(x,t):
    y=np.dot(x,W)+b
    return (np.sum((t-y)**2))/(len(x))

In [22]:
# 미분함수 공식
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) #f(x+delta_x)
        
        x[idx]=tmp_val-delta_x
        fx2=f(x) #f(x-detal_x)
        grad[idx]=(fx1-fx2)/(2*delta_x)
        
        x[idx]=tmp_val
        it.iternext()
        
    return grad

In [16]:
# 손실 함수 값 계산 함수
def error_val(x,t):
    y=np.dot(x,W)+b
    return (np.sum((t-y)**2))/(len(x))

In [17]:
# 학습을 마친 후 임의의 데이터에 대해 미래 값 예측 함수
def predict(x):
    y=np.dot(x,W)+b
    return y

In [25]:
# 발산하는 경우 1e-3 ~ 1e-6 등으로 바꾸어서 실행
# 잘내려가다가 갑자기 올라간다는 등
learning_rate = 1e-2

f = lambda x:loss_func(x_data, t_data)

print('Intitial error value = ', error_val(x_data,t_data))
print('Intitial W = ', W)
print('Intitial b = ', b)

for step in range(8001):
    W -= learning_rate * numerical_derivative(f,W)
    b -= learning_rage * numerical_derivative(f,b)
    
    if( step%400==0):
        print('step=',step, 'error value=',error_val(x_data, t_data),
              'W=',W, 'b=',b)

Intitial error value =  0.4570817929854628
Intitial W =  [[0.88554314]]
Intitial b =  [0.68695527]
step= 0 error value= 0.2741709110357964 W= [[0.92950634]] b= [0.69744578]
step= 400 error value= 0.0008535256409603965 W= [[1.01897165]] b= [0.9315231]
step= 800 error value= 5.445998191367569e-05 W= [[1.00479221]] b= [0.98270285]
step= 1200 error value= 3.4748688120252246e-06 W= [[1.0012105]] b= [0.99563077]
step= 1600 error value= 2.217171735371563e-07 W= [[1.00030577]] b= [0.99889634]
step= 2000 error value= 1.4146866457552e-08 W= [[1.00007724]] b= [0.99972122]
step= 2400 error value= 9.026537158714732e-10 W= [[1.00001951]] b= [0.99992958]
step= 2800 error value= 5.759464353540593e-11 W= [[1.00000493]] b= [0.99998221]
step= 3200 error value= 3.6748787545697495e-12 W= [[1.00000124]] b= [0.99999551]
step= 3600 error value= 2.344789904165764e-13 W= [[1.00000031]] b= [0.99999887]
step= 4000 error value= 1.4961145885978397e-14 W= [[1.00000008]] b= [0.99999971]
step= 4400 error value= 9.5460

In [26]:
predict(10)

array([[11.]])

In [31]:
import numpy as np

load_data = np.loadtxt('data/data-01-test-score.csv',
                      delimiter=',', dtype=np.float32)

x_data = load_data[:,0:-1] #맨마지막 열 빼고
t_data = load_data[:,[-1]] #맨마지막 열 만

x_data
t_data

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.],
       [101.],
       [149.],
       [115.],
       [175.],
       [164.],
       [141.],
       [141.],
       [184.],
       [152.],
       [148.],
       [192.],
       [147.],
       [183.],
       [177.],
       [159.],
       [177.],
       [175.],
       [175.],
       [149.],
       [192.]], dtype=float32)

In [41]:
W = np.random.rand(3,1) #3행 1열
b = np.random.rand(1)

print('W=',W, 'b=',b)

W= [[0.11564407]
 [0.63140751]
 [0.05328893]] b= [0.52874103]


In [42]:
learing_rate = 1e-5

f= lambda x : loss_func(x_data,t_data)

print('Initial error value =',error_val(x_data,t_data), 'Initial W=',W, 'Initial b=',b)

for step in range(10001):
    W-=learning_rate*numerical_derivative(f,W)
    b-=learning_rate*numerical_derivative(f,b)
    
    if(step%400==0):
        print('step=',step,'error value=',error_val(x_data, t_data), '\nW=',W,'\nb=',b,'\n')
    

Initial error value = 9790.7388265398 Initial W= [[0.11564407]
 [0.63140751]
 [0.05328893]] Initial b= [0.52874103]
step= 0 error value= 1435002726.0367522 
W= [[158.00683881]
 [159.2002052 ]
 [162.84445258]] 
b= [-764.45419773] 

step= 400 error value= 7.12257658376883e+29 
W= [[3.42710497e+12]
 [3.50758658e+12]
 [3.50737946e+12]] 
b= [-1.12142771e+08] 

step= 800 error value= 7.12257658376883e+29 
W= [[3.42710497e+12]
 [3.50758658e+12]
 [3.50737946e+12]] 
b= [-1.12142771e+08] 

step= 1200 error value= 7.12257658376883e+29 
W= [[3.42710497e+12]
 [3.50758658e+12]
 [3.50737946e+12]] 
b= [-1.12142771e+08] 

step= 1600 error value= 7.12257658376883e+29 
W= [[3.42710497e+12]
 [3.50758658e+12]
 [3.50737946e+12]] 
b= [-1.12142771e+08] 

step= 2000 error value= 7.12257658376883e+29 
W= [[3.42710497e+12]
 [3.50758658e+12]
 [3.50737946e+12]] 
b= [-1.12142771e+08] 

step= 2400 error value= 7.12257658376883e+29 
W= [[3.42710497e+12]
 [3.50758658e+12]
 [3.50737946e+12]] 
b= [-1.12142771e+08] 

ste

In [43]:
test_data = np.array([100,98,81])

predict(test_data)

array([9.70551606e+14])